// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface Ausbildungsprogramm {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_eyebrow?: string;
  hero_title?: string;
  hero_subtitle?: string;
  hero_primary_cta_text?: string;
  hero_primary_cta_href?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  outcomes_title?: string;
  outcomes?: unknown;
  stage_cards?: unknown;
  narrative2_title?: string;
  narrative2_body?: string;
  narrative2_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  lehrerin_eyebrow?: string;
  lehrerin_title?: string;
  lehrerin_body?: string;
  lehrerin_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  lehrerin_paragraphs?: unknown;
  about_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  about_paragraphs?: unknown;
  info_cards?: unknown;
  schedule_caption?: string;
  testimonials?: unknown;
  testimonials_tone?: "gold" | "spring-wood" | "purple" | "cherrywood";
  teacher?: string;
  faq_items?: unknown;
  infoanlass_eyebrow?: string;
  infoanlass_title?: string;
  infoanlass_body?: string;
  agenda_items?: unknown;
  sections?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface FaqEintrag {
  id: string;
  slug: string | null;
  status: string;
  question?: string;
  answer?: string;
  context?: "praxis-hypnose" | "praxis-aufstellungen" | "praxis-numerologie" | "praxis-fussreflex" | "ausbildung" | "jawort" | "workshop-aktueller" | "workshop-kalender" | "home" | "kontakt" | "neuigkeiten" | "praxisangebote-overview";
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface InfoKarte {
  id: string;
  slug: string | null;
  status: string;
  eyebrow?: string;
  body?: string;
  context?: "praxis-hypnose" | "praxis-aufstellungen" | "praxis-numerologie" | "praxis-fussreflex" | "ausbildung" | "jawort" | "workshop-aktueller" | "workshop-kalender" | "home" | "kontakt" | "neuigkeiten" | "praxisangebote-overview";
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Rechtstext {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  last_updated?: string;
  body_markdown?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface AngebotsKarte {
  id: string;
  slug: string | null;
  status: string;
  icon?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  title?: string;
  description?: string;
  cta_text?: string;
  cta_href?: string;
  context?: "praxis-hypnose" | "praxis-aufstellungen" | "praxis-numerologie" | "praxis-fussreflex" | "ausbildung" | "jawort" | "workshop-aktueller" | "workshop-kalender" | "home" | "kontakt" | "neuigkeiten" | "praxisangebote-overview";
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Seite {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_eyebrow?: string;
  hero_title?: string;
  hero_subtitle?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_primary_cta_text?: string;
  hero_primary_cta_href?: string;
  hero_secondary_cta_text?: string;
  hero_secondary_cta_href?: string;
  hero_paragraphs?: unknown;
  sections?: unknown;
  team_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  team_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  team_image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  value_cards?: unknown;
  outcomes?: unknown;
  stage_cards?: unknown;
  offer_cards?: unknown;
  testimonials_tone?: "gold" | "spring-wood" | "purple" | "cherrywood";
  faq_items?: unknown;
  newsletterhero_paragraphs?: unknown;
  newsletter_placeholder?: string;
  newsletter_submit_text?: string;
  contact_recipient?: string;
  contact_submit_text?: string;
  contact_email_placeholder?: string;
  contact_firstname_placeholder?: string;
  contact_lastname_placeholder?: string;
  contact_message_placeholder?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Praxisangebot {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_category?: string;
  hero_title?: string;
  hero_description?: string;
  hero_duration?: string;
  hero_price?: string;
  hero_note?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_cta_text?: string;
  hero_cta_href?: string;
  price_list?: unknown;
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_bullet_groups?: unknown;
  gallery?: unknown;
  process_steps?: unknown;
  quote_text?: string;
  quote_attribution?: string;
  quote_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonials?: unknown;
  testimonials_tone?: "gold" | "spring-wood" | "purple" | "cherrywood";
  bio_paragraphs?: unknown;
  practitioner?: string;
  brand_cta_title?: string;
  brand_cta_body?: string;
  brand_cta_text?: string;
  brand_cta_href?: string;
  faq_items?: unknown;
  sections?: unknown;
  practice_offers?: unknown;
  newsletter_placeholder?: string;
  newsletter_submit_text?: string;
  claim_cta_text?: string;
  claim_cta_href?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface SiteEinstellung {
  id: string;
  slug: string | null;
  status: string;
  site_title?: string;
  contact_email?: string;
  address?: string;
  nav_items?: unknown;
  footer_columns?: unknown;
  social_links?: unknown;
  footer_legal?: unknown;
  footer_phones?: unknown;
  footer_copyright?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Person {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  eyebrow?: string;
  role?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  bio_paragraphs?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Stimme {
  id: string;
  slug: string | null;
  status: string;
  quote?: string;
  name?: string;
  role?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  context?: "praxis-hypnose" | "praxis-aufstellungen" | "praxis-numerologie" | "praxis-fussreflex" | "ausbildung" | "jawort" | "workshop-aktueller" | "workshop-kalender" | "home" | "kontakt" | "neuigkeiten" | "praxisangebote-overview";
  featured?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface WertKarte {
  id: string;
  slug: string | null;
  status: string;
  icon?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  title?: string;
  body?: string;
  context?: "praxis-hypnose" | "praxis-aufstellungen" | "praxis-numerologie" | "praxis-fussreflex" | "ausbildung" | "jawort" | "workshop-aktueller" | "workshop-kalender" | "home" | "kontakt" | "neuigkeiten" | "praxisangebote-overview";
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Workshop {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  date?: string;
  color?: "gold" | "raspberry" | "lavender" | "fire";
  card_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  card_eyebrow?: string;
  card_title?: string;
  card_description?: string;
  card_duration?: string;
  hero_description?: string;
  hero_price?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  category_meta?: string;
  duration_meta?: string;
  info_cards?: unknown;
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_bullet_groups?: unknown;
  deep_paragraphs?: unknown;
  about_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  about_paragraphs?: unknown;
  testimonials?: unknown;
  testimonials_tone?: "gold" | "spring-wood" | "purple" | "cherrywood";
  faq_items?: unknown;
  category_pills?: unknown;
  sections?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    ausbildung_programs: Ausbildungsprogramm;
    faq: FaqEintrag;
    info_cards: InfoKarte;
    legal: Rechtstext;
    offer_cards: AngebotsKarte;
    pages: Seite;
    praxisangebote: Praxisangebot;
    site_settings: SiteEinstellung;
    team: Person;
    testimonials: Stimme;
    value_cards: WertKarte;
    workshops: Workshop;
  }
}