// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface Ausbildungsprogramm {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_eyebrow?: string;
  hero_title?: string;
  hero_subtitle?: string;
  hero_primary_cta_text?: string;
  hero_primary_cta_href?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  outcomes_title?: string;
  outcomes?: unknown;
  narrative2_title?: string;
  narrative2_body?: string;
  narrative2_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  lehrerin_eyebrow?: string;
  lehrerin_title?: string;
  lehrerin_body?: string;
  lehrerin_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  about_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  info_cards?: unknown;
  schedule_caption?: string;
  testimonials?: unknown;
  teacher?: string;
  faq_items?: unknown;
  infoanlass_eyebrow?: string;
  infoanlass_title?: string;
  infoanlass_body?: string;
  sections?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Rechtstext {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  last_updated?: string;
  body_markdown?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Seite {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_eyebrow?: string;
  hero_title?: string;
  hero_subtitle?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_primary_cta_text?: string;
  hero_primary_cta_href?: string;
  hero_secondary_cta_text?: string;
  hero_secondary_cta_href?: string;
  sections?: unknown;
  team_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  team_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  team_image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Praxisangebot {
  id: string;
  slug: string | null;
  status: string;
  seo_title?: string;
  seo_description?: string;
  hero_category?: string;
  hero_title?: string;
  hero_description?: string;
  hero_duration?: string;
  hero_price?: string;
  hero_note?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_cta_text?: string;
  hero_cta_href?: string;
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_bullet_groups?: unknown;
  process_steps?: unknown;
  quote_text?: string;
  quote_attribution?: string;
  quote_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonials?: unknown;
  practitioner?: string;
  brand_cta_title?: string;
  brand_cta_body?: string;
  brand_cta_text?: string;
  brand_cta_href?: string;
  faq_items?: unknown;
  sections?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface SiteEinstellung {
  id: string;
  slug: string | null;
  status: string;
  site_title?: string;
  site_description?: string;
  default_og_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  contact_email?: string;
  contact_phone?: string;
  address?: string;
  nav_items?: unknown;
  footer_columns?: unknown;
  social_links?: unknown;
  newsletter_eyebrow?: string;
  newsletter_title?: string;
  newsletter_body?: string;
  newsletter_placeholder?: string;
  newsletter_submit_text?: string;
  footer_legal?: unknown;
  footer_phones?: unknown;
  footer_copyright?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Person {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  eyebrow?: string;
  role?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  bio_paragraphs?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Workshop {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  date?: string;
  color?: "gold" | "raspberry" | "lavender" | "fire";
  category_meta?: string;
  duration_meta?: string;
  hero_description?: string;
  hero_price?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  info_cards?: unknown;
  narrative_title?: string;
  narrative_body?: string;
  narrative_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  narrative_bullet_groups?: unknown;
  testimonials?: unknown;
  about_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  faq_items?: unknown;
  further_courses?: unknown;
  card_eyebrow?: string;
  card_title?: string;
  card_description?: string;
  card_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  card_duration?: string;
  sections?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    ausbildung_programs: Ausbildungsprogramm;
    legal: Rechtstext;
    pages: Seite;
    praxisangebote: Praxisangebot;
    site_settings: SiteEinstellung;
    team: Person;
    workshops: Workshop;
  }
}