import { defineMiddleware, sequence } from 'astro:middleware';
import { sparkEmdash } from 'spark-emdash/middleware';
// Per-page "which top-level fields does this entry's page actually read" map,
// generated by scripts/gen-used-fields.cjs. Drives the admin field hiding below.
import usedFields from './lib/used-fields.json';

const USED_FIELDS_JSON = JSON.stringify(usedFields).replace(/</g, '\\u003c');

/**
 * Admin UX enhancement: when an editor clicks "Add Item" in a repeater field,
 * scroll the newly added row into view and focus its first input.
 *
 * The EmDash admin is a third-party SPA (@emdash-cms/admin) served from
 * node_modules, so we can't edit it directly. Instead we inject a tiny client
 * script into the admin HTML shell here — this survives EmDash upgrades because
 * it only depends on the public DOM shape (an "Add Item" button whose repeater
 * renders its rows in a `.space-y-2` list), not on internal package code.
 */
const SCROLL_ON_ADD = `<script>(function(){
  if (window.__emdashScrollAddInstalled) return;
  window.__emdashScrollAddInstalled = true;
  function isAddBtn(b){
    if(!b) return false;
    var t=(b.textContent||'').trim().toLowerCase();
    return t==='add item' || t==='add first item';
  }
  function list(root){
    return root.querySelector(':scope > .space-y-2') || root.querySelector('.space-y-2');
  }
  document.addEventListener('click', function(e){
    var b = e.target && e.target.closest && e.target.closest('button');
    if(!isAddBtn(b)) return;
    var root = b.parentElement && b.parentElement.parentElement;
    if(!root) return;
    var l0 = list(root);
    var before = l0 ? l0.children.length : 0;
    var start = performance.now();
    (function tick(){
      var l = list(root);
      if (l && l.children.length > before) {
        var item = l.children[l.children.length - 1];
        if (item) {
          item.scrollIntoView({ behavior: 'smooth', block: 'center' });
          var f = item.querySelector('input,textarea,select,[contenteditable="true"]');
          if (f) { try { f.focus({ preventScroll: true }); } catch(_){} }
        }
        return;
      }
      if (performance.now() - start < 1000) requestAnimationFrame(tick);
    })();
  }, true);
})();</script>`;

/**
 * ONE consolidated admin-editor enhancer (replaces the former separate
 * type-aware / info-note observers). A SINGLE MutationObserver drives everything,
 * and it DISCONNECTS while it mutates the DOM so its own insertions/toggles never
 * re-trigger it — this removes the observer-churn (multiple observers each
 * reacting to the others' node insertions) that made editing feel unstable.
 *
 * It does, in one pass per (debounced) DOM change:
 *  1. Type-aware section fields — hide sub-fields a block type doesn't use.
 *  2. Content hints — tell the editor where each list block's content is edited.
 *  3. Per-page top-level field hiding (used-fields map) + "Weitere Felder" toggle.
 *  4. Info-note banner on pages that DISPLAY workshop cards.
 *  5. Hide "Add Item" on pages that don't render <Blocks> (non-dynamic pages),
 *     so blocks can only be added where they actually work.
 *
 * Same safety class as spark-emdash: it only toggles CSS `display` and inserts its
 * own marked nodes — it never reparents React-managed nodes, and the disconnect
 * guard keeps React reconciliation and this script from fighting each other.
 */
const ADMIN_ENHANCE = `<script>(function(){
  if (window.__emdashAdmin) return;
  window.__emdashAdmin = true;

  // Which top-level fields each entry's page actually reads (collection/slug -> labels).
  var USED = ${USED_FIELDS_JSON};

  // Pages that render <Blocks> (support freely adding/reordering blocks). Every
  // other entry is a fixed layout, so "Add Item" is hidden there.
  var DYNAMIC = { 'pages/home':1, 'pages/kontakt':1, 'pages/neuigkeiten':1, 'praxisangebote/overview':1 };

  // Sub-fields each supported block type actually renders (see Blocks.astro).
  // Unlisted types (legacy sec-bag types like hero/intro/team/stages/quote, or
  // bespoke gallery/price_list) => show every field, so we never hide a field a type
  // we don't model might use. Collections whose sections have no 'context'
  // sub-field (ausbildung_programs/workshops) simply ignore the 'context' entry.
  var SHOW = {
    narrative:       ['eyebrow','title','body','image','image_side','tone'],
    featured:        ['eyebrow','title','body','image','image_side','tone'],
    overview_hero:   ['eyebrow','title','body','image'],
    // Context-resolved (content lives in a shared collection picked by Kontext):
    testimonials:    ['eyebrow','title','context'],
    info_cards:      ['eyebrow','title','context'],
    offer_cards:     ['eyebrow','title','context'],
    // Inline (content edited in the page's own Werte-Karten / FAQ list) — no Kontext:
    value_cards:     ['eyebrow','title'],
    process_steps:   ['eyebrow','title'],
    faq:             ['title','tone'],
    newsletter:      ['eyebrow','title','body'],
    newsletter_hero: ['eyebrow','title','image'],
    person_bio:      ['eyebrow','title','image','image_side'],
    claim_block:     ['title','body','image'],
    dark_cta:        ['eyebrow','title','body','image'],
    practice_offers: [],
    contact_form:    [],
    // Bespoke sec-bag types on ausbildung_programs / workshops / ueber-uns overview
    // pages (fields read by the page code; the rest of the shared set is unused).
    hero:            ['eyebrow','title','body','image'],
    intro:           ['title','body','image'],
    stages:          ['title','body'],
    outcomes:        ['title'],
    lehrerin:        ['eyebrow','title','image'],
    uquote:          ['title','body','image'],
    about:           ['title','image']
  };
  // The 4 combobox sub-fields render in this fixed schema order per row.
  var COMBO_ORDER = ['type','image_side','tone','context'];

  // Where each list block's ACTUAL content is edited (it can't live in the row).
  // Shown as a small hint at the top of the row so editors know where to go.
  var HINTS = {
    value_cards:  'Inhalt: die Liste „Werte-Karten" weiter unten auf dieser Seite bearbeiten.',
    faq:          'Inhalt: die Liste „Häufige Fragen (FAQ)" weiter unten auf dieser Seite bearbeiten.',
    testimonials: 'Inhalt: aus der Sammlung „Stimmen" — passenden Kontext wählen.',
    info_cards:   'Inhalt: aus der Sammlung „Info-Karten" — passenden Kontext wählen.',
    offer_cards:  'Inhalt: aus der Sammlung „Angebots-Karten" — passenden Kontext wählen.'
  };

  function txt(el){ return (el && el.textContent || '').replace(/\\s+/g,' ').trim(); }
  function labelKey(t){
    t = t.toLowerCase();
    if (t.indexOf('eyebrow') === 0) return 'eyebrow';
    if (t.indexOf('titel') === 0) return 'title';
    if (t === 'text') return 'body';
    if (t.indexOf('bild') === 0) return 'image';
    return null;
  }
  function setDisp(el, show){
    var d = show ? '' : 'none';
    if (el && el.style.display !== d) el.style.display = d;
  }

  function processRow(row){
    var body = row.querySelector('.p-3.space-y-3');
    if (!body) return; // collapsed row: nothing rendered to toggle
    // Each body child is one sub-field wrapper. Text/select fields use a .grid
    // wrapper with a <label>; the image ("Bild") uploader uses a different
    // wrapper with no .grid class — so match on "contains a label or combobox"
    // rather than a class, otherwise the image field is never toggled.
    var wraps = Array.prototype.filter.call(body.children, function(c){
      return c.querySelector && (c.querySelector('button[role=combobox]') || c.querySelector('label'));
    });
    var byKey = {}, ci = 0;
    wraps.forEach(function(w){
      if (w.querySelector('button[role=combobox]')) { byKey[COMBO_ORDER[ci++]] = w; return; }
      var lab = w.querySelector('label');
      var k = lab ? labelKey(txt(lab)) : null;
      if (k) byKey[k] = w;
    });
    if (!byKey.type) return;
    var combo = byKey.type.querySelector('button[role=combobox]');
    var type = combo ? txt(combo) : '';
    var show = SHOW[type];
    Object.keys(byKey).forEach(function(k){
      if (k === 'type') { setDisp(byKey[k], true); return; }
      setDisp(byKey[k], !show ? true : show.indexOf(k) > -1);
    });
    // Content hint: tell the editor where this list block's content is edited.
    var hint = HINTS[type];
    var el = body.querySelector('.emd-type-hint');
    if (!hint) { if (el) el.parentNode.removeChild(el); }
    else if (!el || el.getAttribute('data-type') !== type) {
      if (el) el.parentNode.removeChild(el);
      el = document.createElement('div');
      el.className = 'emd-type-hint';
      el.setAttribute('data-type', type);
      el.style.cssText = 'margin:2px 0 6px;padding:6px 10px;font-size:12px;line-height:1.4;color:#5c4326;background:#fbf5e9;border-left:3px solid #c79a3b;border-radius:6px;';
      el.textContent = 'ℹ️ ' + hint;
      body.insertBefore(el, body.firstChild);
    }
  }

  // ---- top-level field visibility (per page) -------------------------------
  // Show only the fields THIS entry's page actually reads (from USED), plus any field
  // that already holds data (safety net for cross-page fields like a workshop's
  // calendar-card), plus the "Sektionen" block builder. Everything else — the unused
  // shared-schema clutter that does nothing when filled — is hidden behind the
  // "Weitere Felder" toggle. Without a map for the entry we fall back to hiding only
  // obvious empty clutter, so unknown editors still degrade gracefully.
  var showAllTop = false;
  function norm(name){
    return name.replace(/\\(optional\\)/ig,'').replace(/\\(\\d+\\s*items?\\)/ig,'').replace(/\\(no items yet\\)/ig,'').trim();
  }
  function currentContext(){
    var m = location.pathname.match(/\\/content\\/([^\\/]+)\\//);
    var coll = m ? m[1] : '';
    var slug = '';
    var si = document.querySelector('input[name="slug" i], input[id="slug" i]');
    if (si && si.value) slug = si.value;
    if (!slug){
      var labels = document.querySelectorAll('label');
      for (var i=0;i<labels.length;i++){
        if (txt(labels[i]) === 'Slug'){
          var inp = labels[i].parentElement && labels[i].parentElement.querySelector('input');
          if (inp){ slug = inp.value; break; }
        }
      }
    }
    return { coll: coll, key: coll + '/' + slug };
  }
  function allowedFor(){
    var ctx = currentContext();
    var e = USED.explicit && USED.explicit[ctx.key];
    if (e) return e;
    return (USED.dynamic && USED.dynamic[ctx.coll]) || null; // null => no map => fallback
  }
  function topColumn(){
    var secLabel = Array.prototype.find.call(document.querySelectorAll('label'), function(l){ return txt(l).indexOf('Sektionen') === 0; });
    if (!secLabel) return null;
    var col = secLabel;
    for (var i=0;i<12 && col;i++){ if (col.classList && col.classList.contains('space-y-4')) break; col = col.parentElement; }
    return (col && col.classList && col.classList.contains('space-y-4')) ? col : null;
  }
  function hasData(w){
    var inner = w.querySelector('.space-y-2');
    if (inner != null) return inner.children.length > 0;
    if (/no items yet/i.test(txt(w))) return false;
    if (w.querySelector('img')) return true;
    var inp = w.querySelector('input:not([type=hidden]):not([type=file]),textarea');
    if (inp) return !!inp.value;
    var combo = w.querySelector('button[role=combobox]');
    if (combo){ var t = txt(combo); return !!t && t.toLowerCase().indexOf('select') !== 0; }
    return false;
  }
  // Fallback (no page map): hide only obvious empty clutter.
  function isEmptyClutter(w){
    var inner = w.querySelector('.space-y-2');
    if (inner != null || /no items yet/i.test(txt(w))) return inner ? inner.children.length === 0 : true;
    var lab = w.querySelector('label'); var lt = lab ? txt(lab).toLowerCase() : '';
    if (/foto|bild|logo|graphic|grafik|image/.test(lt) || w.querySelector('input[type=file]')) return !w.querySelector('img');
    var inp = w.querySelector('input:not([type=hidden]):not([type=file]),textarea');
    if (inp) return !inp.value && /platzhalter|placeholder/.test(lt);
    return false;
  }
  function applyTop(){
    var col = topColumn();
    if (!col) return;
    var allowed = allowedFor();
    Array.prototype.forEach.call(col.children, function(w){
      if (w.id === 'emd-more-fields') return;
      var lab = w.querySelector('label');
      var name = lab ? norm(txt(lab)) : '';
      if (/^sektionen/i.test(name)) { setDisp(w, true); return; } // always show the builder
      var keep = allowed ? (allowed.indexOf(name) > -1 || hasData(w)) : !isEmptyClutter(w);
      setDisp(w, keep || showAllTop);
    });
    ensureToggle(col);
  }
  function ensureToggle(col){
    if (document.getElementById('emd-more-fields')) return;
    var b = document.createElement('button');
    b.id = 'emd-more-fields'; b.type = 'button';
    b.textContent = '+ Weitere (leere) Felder anzeigen';
    b.style.cssText = 'margin-top:8px;font-size:13px;color:#8a6d3b;background:none;border:1px dashed #cbb994;border-radius:8px;padding:6px 12px;cursor:pointer;';
    b.addEventListener('click', function(){
      showAllTop = !showAllTop;
      b.textContent = showAllTop ? '– Leere Felder ausblenden' : '+ Weitere (leere) Felder anzeigen';
      applyTop();
    });
    col.appendChild(b);
  }

  // Only process rows inside a "Sektionen" repeater list — a global class match
  // also catches unrelated cards (Ownership, other repeaters) on the page.
  function sectionRows(){
    var rows = [];
    Array.prototype.forEach.call(document.querySelectorAll('label'), function(l){
      if (txt(l).indexOf('Sektionen') !== 0) return;
      var cont = l.parentElement, list = null;
      for (var i=0;i<8 && cont;i++){ list = cont.querySelector('.space-y-2'); if (list) break; cont = cont.parentElement; }
      if (list) Array.prototype.push.apply(rows, Array.prototype.slice.call(list.children));
    });
    return rows;
  }
  // ---- info-note banner (pages that DISPLAY workshop cards) ---------------
  var WORKSHOP_CARDS = 'Die Workshop-Karten auf dieser Seite („Nächste/Weitere Kurse und Workshops") '
    + 'stammen automatisch aus der Sammlung „Workshops & Kurse" (die Workshops mit Datum, nach Datum '
    + 'sortiert) — sie werden NICHT hier bearbeitet. Zum Ändern die jeweiligen Workshops öffnen und deren '
    + '„Kalenderkarte"-Felder anpassen.';
  var NOTES = {
    'ausbildung_programs/infoanlaesse':        WORKSHOP_CARDS,
    'workshops/kalender-uebersicht':           WORKSHOP_CARDS,
    'workshops/soultap-gegen-angst':           WORKSHOP_CARDS,
    'workshops/vagusnerv-ruhe':                WORKSHOP_CARDS,
    'workshops/cool-down-for-christmas':       WORKSHOP_CARDS,
    'workshops/adventsgeschichten':            WORKSHOP_CARDS
  };
  function applyNote(){
    var key = currentContext().key;
    var note = NOTES[key];
    var el = document.getElementById('emd-info-note');
    if (!note){ if (el) el.parentNode.removeChild(el); return; }        // not a card page
    if (el){ if (el.getAttribute('data-key') === key) return; el.parentNode.removeChild(el); }
    var col = topColumn();
    if (!col) return;
    var box = document.createElement('div');
    box.id = 'emd-info-note';
    box.setAttribute('data-key', key);
    box.style.cssText = 'margin:0 0 16px;padding:12px 14px;font-size:13px;line-height:1.5;color:#5c4326;'
      + 'background:#fbf5e9;border:1px solid #e3cfa3;border-left:4px solid #c79a3b;border-radius:8px;';
    box.textContent = 'ℹ️ ' + note;
    col.insertBefore(box, col.firstChild);
  }

  // ---- hide "Add Item" on non-dynamic pages -------------------------------
  // Find the Sektionen repeater field wrapper (ancestor holding both the row
  // list and an add button), then hide the add button unless this is a page
  // that actually renders <Blocks>.
  function sektionenField(){
    var secLabel = Array.prototype.find.call(document.querySelectorAll('label'), function(l){ return txt(l).indexOf('Sektionen') === 0; });
    if (!secLabel) return null;
    var w = secLabel.parentElement;
    for (var i=0;i<10 && w;i++){
      if (w.querySelector && w.querySelector('.space-y-2')){
        var bs = w.querySelectorAll('button');
        for (var j=0;j<bs.length;j++){ var t=(bs[j].textContent||'').trim().toLowerCase(); if (t==='add item'||t==='add first item') return w; }
      }
      w = w.parentElement;
    }
    return null;
  }
  function applyBuilder(){
    var dyn = !!DYNAMIC[currentContext().key];
    var w = sektionenField();
    if (!w) return;
    Array.prototype.forEach.call(w.querySelectorAll('button'), function(b){
      var t=(b.textContent||'').trim().toLowerCase();
      if (t==='add item' || t==='add first item') setDisp(b, dyn);
    });
  }

  // ---- single self-guarded pass -------------------------------------------
  // ONE observer for everything; it disconnects while it writes so its own
  // insertions/toggles never re-trigger it (no observer churn / flicker).
  var observer, pending = false;
  function apply(){
    if (observer) observer.disconnect();
    try {
      sectionRows().forEach(function(row){
        if (row.querySelector && row.querySelector('button[role=combobox]')) processRow(row);
      });
      applyTop();
      applyNote();
      applyBuilder();
    } catch(e){}
    if (observer) observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  }
  // Debounce with setTimeout (rAF is paused in background/unfocused tabs).
  function schedule(){ if (pending) return; pending = true; setTimeout(function(){ pending = false; apply(); }, 80); }
  observer = new MutationObserver(schedule);
  observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  schedule();
})();</script>`;

const scrollOnAdd = defineMiddleware(async (context, next) => {
  const res = await next();
  const { pathname } = new URL(context.request.url);
  const contentType = res.headers.get('content-type') || '';

  if (pathname.startsWith('/_emdash/admin') && contentType.includes('text/html')) {
    const html = await res.text();
    if (html.includes('</body>') && !html.includes('__emdashScrollAddInstalled')) {
      const headers = new Headers(res.headers);
      headers.delete('content-length'); // body length changes after injection
      return new Response(html.replace('</body>', SCROLL_ON_ADD + ADMIN_ENHANCE + '</body>'), {
        status: res.status,
        statusText: res.statusText,
        headers,
      });
    }
    // Already injected or no body marker — return the (already read) HTML as-is,
    // but drop content-length: spark-emdash (upstream in the sequence) still
    // grows the body by injecting before </head> and reuses these headers.
    const headers = new Headers(res.headers);
    headers.delete('content-length');
    return new Response(html, { status: res.status, statusText: res.statusText, headers });
  }

  return res;
});

/**
 * spark-emdash upgrades the EmDash admin editing experience (wider modals,
 * scrollable forms, JSON/markdown editors, char counts, change tracking,
 * dark mode, and block-card previews). It only injects CSS + a MutationObserver
 * that sets CSS `order`/`grid-column` — it never reparents React-managed nodes,
 * so it survives EmDash upgrades and doesn't fight React reconciliation.
 *
 * The installed spark-emdash@0.6.0 is tuned for VitaLunaris (its card previews
 * know our `on-sky`/`spring-wood` tones). Zero-config for now — the base UX fixes
 * apply to our `sections`-repeater editors out of the box. Add `layouts` /
 * `illustrations` / `previews` here once we confirm exact modal field labels.
 *
 * sequence() runs spark first (injects before </head>), then scrollOnAdd
 * (injects before </body>); each returns a fresh Response, so both patches land.
 */
export const onRequest = sequence(sparkEmdash(), scrollOnAdd);
